environment: default
queue:
  name: server-condenser-test
  host: localhost
worker-threads-quantity: 16
port: 4500
---
environment: test
---
environment: stage
queue:
  name: server-condenser-staging
---
environment: prod
queue:
  name: server-condenser-prod