tix-time-server:
  queue-name: server-condenser-test
  queue-host: localhost
  worker-threads-quantity: 16
  port: 4500
---
spring:
  profiles: test
tix-time-server:
  queue-name: server-condenser-test
  port: ${random.int([1025, 8192])}
---
spring:
  profiles: staging
---
spring:
  profiles: production